/// ═══════════════════════════════════════════════════════════════════════════════
/// journal_entry_model.dart — Data Model for Farm Journal Entries
/// ═══════════════════════════════════════════════════════════════════════════════
///
/// Maps to the `journal_entries` table in Supabase. Each entry has a title,
/// content body, and auto-generated timestamp used as the display date.
///
/// Fields:
///   - id: UUID primary key (auto-generated by Supabase)
///   - userId: UUID foreign key to the authenticated user
///   - title: Entry headline (e.g., 'Irrigation Check')
///   - content: Body text of the journal entry
///   - createdAt: Timestamp, also used as the display date in the feed
/// ═══════════════════════════════════════════════════════════════════════════════

class JournalEntryModel {
  final String? id;
  final String? userId;
  final String title;
  final String content;
  final DateTime? createdAt;

  JournalEntryModel({
    this.id,
    this.userId,
    required this.title,
    required this.content,
    this.createdAt,
  });

  /// Creates a JournalEntryModel from a Supabase row (JSON map).
  factory JournalEntryModel.fromJson(Map<String, dynamic> json) {
    return JournalEntryModel(
      id: json['id'] as String?,
      userId: json['user_id'] as String?,
      title: json['title'] as String? ?? 'Untitled',
      content: json['content'] as String? ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
    );
  }

  /// Converts to a JSON map for Supabase INSERT.
  /// Excludes `id` and `created_at` (auto-managed by Supabase).
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'content': content,
      // user_id is set automatically via RLS (auth.uid())
    };
  }

  /// Returns a formatted date string for display (e.g., 'OCT 24, 2023').
  String get formattedDate {
    if (createdAt == null) return 'TODAY';
    const months = [
      'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
      'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC',
    ];
    return '${months[createdAt!.month - 1]} ${createdAt!.day}, ${createdAt!.year}';
  }
}
