/// ═══════════════════════════════════════════════════════════════════════════════
/// specimen_model.dart — Data Model for Palm Specimens
/// ═══════════════════════════════════════════════════════════════════════════════
///
/// Maps to the `specimens` table in Supabase. Provides serialization helpers
/// for converting between Dart objects and Supabase JSON rows.
///
/// Fields:
///   - id: UUID primary key (auto-generated by Supabase)
///   - userId: UUID foreign key to the authenticated user
///   - variety: Date palm cultivar name (e.g., 'MEDJOOL', 'BARHI')
///   - originDate: When the tree was planted/pollinated
///   - plotLocation: Free-text grove/section location
///   - vitalityNote: Initial health assessment text
///   - createdAt: Timestamp of when the record was created
///   - activeDisease: The name of the disease currently assigned for treatment (null if none)
///   - treatmentStartDate: The date the active treatment began (null if none)
/// ═══════════════════════════════════════════════════════════════════════════════

class SpecimenModel {
  final String? id;
  final String? userId;
  final String variety;
  final DateTime originDate;
  final String plotLocation;
  final String vitalityNote;
  final DateTime? createdAt;
  final String? activeDisease;
  final DateTime? treatmentStartDate;

  SpecimenModel({
    this.id,
    this.userId,
    required this.variety,
    required this.originDate,
    required this.plotLocation,
    this.vitalityNote = '',
    this.createdAt,
    this.activeDisease,
    this.treatmentStartDate,
  });

  /// Creates a SpecimenModel from a Supabase row (JSON map).
  factory SpecimenModel.fromJson(Map<String, dynamic> json) {
    return SpecimenModel(
      id: json['id'] as String?,
      userId: json['user_id'] as String?,
      variety: json['variety'] as String? ?? 'UNKNOWN',
      originDate: DateTime.parse(json['origin_date'] as String),
      plotLocation: json['plot_location'] as String? ?? 'Unspecified',
      vitalityNote: json['vitality_note'] as String? ?? '',
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
      activeDisease: json['active_disease'] as String?,
      treatmentStartDate: json['treatment_start_date'] != null
          ? DateTime.parse(json['treatment_start_date'] as String)
          : null,
    );
  }

  /// Converts to a JSON map for Supabase INSERT/UPDATE.
  /// Excludes `id` and `created_at` (auto-managed by Supabase).
  Map<String, dynamic> toJson() {
    return {
      'variety': variety,
      'origin_date': originDate.toIso8601String().split('T').first,
      'plot_location': plotLocation,
      'vitality_note': vitalityNote,
      'active_disease': activeDisease,
      'treatment_start_date': treatmentStartDate?.toIso8601String().split('T').first,
      // user_id is set automatically via RLS (auth.uid())
    };
  }

  /// Converts to the legacy Map<String, String> format used by existing UI widgets.
  /// This allows gradual migration — screens can keep using Map<String, String>
  /// while the data source switches to the database.
  Map<String, String> toLegacyMap() {
    return {
      'variety': variety,
      'originDate': originDate.toIso8601String(),
      'plot': plotLocation,
      'vitality': vitalityNote,
      if (activeDisease != null) 'activeDisease': activeDisease!,
      if (treatmentStartDate != null) 'treatmentStartDate': treatmentStartDate!.toIso8601String(),
    };
  }

  /// Creates a SpecimenModel from the legacy Map<String, String> format
  /// returned by SpecimenLogScreen.
  factory SpecimenModel.fromLegacyMap(Map<String, String> map) {
    return SpecimenModel(
      variety: map['variety'] ?? 'UNKNOWN',
      originDate: DateTime.tryParse(map['originDate'] ?? '') ?? DateTime.now(),
      plotLocation: map['plot'] ?? 'Unspecified',
      vitalityNote: map['vitality'] ?? '',
      activeDisease: map['activeDisease'],
      treatmentStartDate: map['treatmentStartDate'] != null ? DateTime.tryParse(map['treatmentStartDate']!) : null,
    );
  }
}
